baseURL = 'https://hykrion.github.io/arduino-tcl-tk/'

languageCode = 'es-es'
title = 'Arduino Tcl/Tk'
theme = 'relearn'

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = true

[languages]

  [languages.es]
    contentDir = "content/es"
    label = "Español"
    locale = "es-ES"
    title = "Arduino y Tcl/Tk"
    weight = 1

  [languages.en]
    contentDir = "content/en"
    label = "English"
    locale = "en-US"
    title = "Arduino and Tcl/Tk"
    weight = 2
    
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.parser]
#      [markup.goldmark.parser.attribute]
#        block = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true